### ISSUE TITLE
adal-node is broken with Webpack.  This seems to fix it.

### ISSUE THREAD

**Issue by dukedougal** [AzureAD/azure-activedirectory-library-for-nodejs#100]
Webpack seems to have a problem with the way adal uses underscore to create the exports.

So in adal.js, remove the following two lines:

> var _ = require('underscore');
> _.extend(exports, authParams);

And instead of the above two lines, explicitly export the required functions, like so

```
exports.createAuthenticationParametersFromUrl = authParams.createAuthenticationParametersFromUrl
exports.createAuthenticationParametersFromResponse = authParams.createAuthenticationParametersFromResponse
exports.createAuthenticationParametersFromHeader = authParams.createAuthenticationParametersFromHeader
exports.AuthenticationParameters = authParams.AuthenticationParameters
```

As far as I can tell this fixes at least one problem working with Webpack.

**Comment by weijjia** [comment]
Sorry i'm not quite familiar with webpack. What is exact problem webpack complains?

**Comment by dukedougal** [comment]
It won't build with webpack. You could try building it with webpack to see the error.

**Comment by AnasTawfeek** [comment]
Still no news about using this with Webpack? that update didn't quite work

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
