### ISSUE TITLE
dependency update of node-uuid to 1.4.3+

### ISSUE THREAD

**Issue by encodeering** [AzureAD/azure-activedirectory-library-for-nodejs#103]
Hello,

we are using browserify for this project and the target platform uses AMD as well, which leads to an _unresolved dependency_ problem for uuid.v4 ()

It seems, that node-uuid has made a correction broofa/node-uuid@7cc55a5 for this issue, prefering exports over define

Do you think an update to at least 1.4.3 would be appropriate for you?

**Comment by weijjia** [comment]
It's already updated to 1.4.7, change is merged into dev. We'll update the master with next release.

**Comment by encodeering** [comment]
Current release notes state, that the update is already available, but I couldn't find it in [v0.1.19](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/v0.1.19/package.json)

Will it be available with the next candidate? Thanks in advance
