### ISSUE TITLE
Does this Library support being used against ADFS

### ISSUE THREAD

**Issue by MarkDordoy-JustEat** [AzureAD/azure-activedirectory-library-for-nodejs#118]
This is a question rather than an issue. I just want clarification on if this library can be used against an ADFS authority rather than an Azure AD authority. 

Thanks

**Comment by addev-ashish** [comment]
Yes, you can. Just pass the ADFS path as the authority and do the username/password flow. https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/sample/username-password-sample.js
