### ISSUE TITLE
acquireTokenWithUsernamePassword return positive result even after wrong password is passed

### ISSUE THREAD

**Issue by murdockcrc** [AzureAD/azure-activedirectory-library-for-nodejs#123]
I have written a mocha test with the current flow:

- use ```acquireTokenWithUsernamePassword``` with correct username and password
- use ```acquireTokenWithUsernamePassword``` with same username but wrong password

The first test passes successfully. For the second test, I am expecting to receive a 400 error response. However, it seems that the function is taking the cached token from the first (successful) authentication request, so I am received a 200 response, even though I am passing the wrong password deliberately. 

I was wondering if this is the behavior by design? Otherwise, how can I use the library to authenticate users in a reliable way?

**Comment by feons** [comment]
@murdockcrc, have you tried setting the token cache used by the `AuthenticationContext` instance?  Specifically the 3rd param, i.e.`new AuthenticationContext(authority, validateAuthority, tokenCacheUsed)`

**Comment by tinkusam** [comment]
I am facing the same problem. I switched from ADL OAuth to Username/Passsword authentication due to limited validity / unpredictable expiry of ADL refresh tokens. Now this issue seems to be another blow!

**Comment by tinkusam** [comment]
@feons  Can I disable the token cache? Anything can be set for third param `tokenCacheUsed` to do that?

**Comment by tinkusam** [comment]
I think the following issue is similar to this
 [https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/460](url)

**Comment by tinkusam** [comment]
@murdockcrc I am seeing a work around by passing `new MemoryCache()` as the third parameter (`tokenCacheUsed`) to `AuthenticationContext`. Now it works for the time being.

**Comment by murdockcrc** [comment]
@feons no, but looking at the source I back-pedaled to that third parameter, I don't think the documentation is clear about the structure of token cache and how to use it/implement it correctly.

If I understand this correctly, one would have to implement a token cache service that effectively caches nothing for this to work as an authentication library? My expectation would be for the API to be an authentication service, otherwise how do you control that a user passing in wrong credentials won't be mistakenly given a valid token?

**Comment by feons** [comment]
@murdockcrc, looking at https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/lib/authentication-context.js#L79-L86, specifically: 

> To control the scope and lifetime of a cache you can either create a MemoryCache instance and pass it when  constructing an AuthenticationContext or implement a custom TokenCache and pass that.

So I think one of the options would be to pass `new adal.MemoryCache`.

**Comment by addev-ashish** [comment]
@murdockcrc What is the end goal of this design? are you expecting to validate username and password every time a token is requested? 
I would think the flow should be acquireTokenWithUsernamePassword  followed by acquireTokenWithRefreshToken and revoking of access be controlled at the azure portal.

**Comment by murdockcrc** [comment]
The intended scenario is to authenticate AAD users on a NodeJS app (not Express). That's why I'm trying to get the library get tokens for users that validate with username and password. Obviously, if a user enters the wrong credentials, then no token should be returned and instead an authentication failed should be triggered. That's the end scenario we're pursuing


Get Outlook for Android






On Tue, Jul 12, 2016 at 7:30 PM +0200, "Ashish Mishra" <notifications@github.com> wrote:





@murdockcrc What is the end goal of this design? are you expecting to validate username and password every time a token is requested?
I would think the flow should be acquireTokenWithUsernamePassword  followed by acquireTokenWithRefreshToken and revoking of access be controlled at the azure portal.

---

**Comment by addev-ashish** [comment]
@murdockcrc our libraries are not meant to validate username and password, we try our best to avoid prompts to the user. But if you want to do this, you can either pass null as the tokencache param or pass in a new one everytime as suggested by @feons.

**Comment by addev-ashish** [comment]
@murdockcrc kindly reopen this issue if you think this resolution does not work for you.
