### ISSUE TITLE
Ignore the test folder from being published to npm

### ISSUE THREAD

**Issue by amishra-dev** [AzureAD/azure-activedirectory-library-for-nodejs#125]
Add .npmignore to ignore the test folder. 
And alternative would be to do a files element in package.json but that has the potential to get overridden by .npmignore, so we will not do that. https://docs.npmjs.com/files/package.json#files

**Comment by jmckennon** [comment]
This is currently implemented.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
