### ISSUE TITLE
Update author information (remove MSOpenTech?)

### ISSUE THREAD

**Issue by jeffwilcox** [AzureAD/azure-activedirectory-library-for-nodejs#129]
Both in `package.json` and throughout this project, copyright references are to the former MSOpenTech entity. Consider seeing whether this can be updated to Microsoft.

**Comment by jeffwilcox** [comment]
Hi, any updates on this? It's been over a year, and the legal entity Microsoft Open Technologies, Inc. was spun down.

**Comment by jmckennon** [comment]
@negoe @DarylThayil -- is this something we should be changing? Basically every file references:
```
 * @copyright
 * Copyright © Microsoft Open Technologies, Inc.
```

https://msopentech.com (referenced in `package.json` does redirect to the https://opensource.microsoft.com site, though.

**Comment by DarylThayil** [comment]
@jmckennon  If you look at the msal core code, the copy write in those files can be replaced here, although it may not be worth it for this codebase.

**Comment by jasonnutter** [comment]
Probably a good thing to do if/when we move this library to the msal repo.

**Comment by sameerag** [comment]
We have addressed this in [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) with the below snippet:

``` javascript
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */
```

Closing.
