### ISSUE TITLE
Token cache stops working and it sometimes takes over a second to get a token

### ISSUE THREAD

**Issue by jngli** [AzureAD/azure-activedirectory-library-for-nodejs#139]
During one of our service runs, we noticed that the token cache stops working after a while and it takes significant time to get a token back, sometime it can be over 2 seconds.

**Comment by prowe** [comment]
If a request for a token is in-flight (awaiting a response from AD) and another token is requested then two responses are received from the AD server. These two responses will have the same _clientId, _authority, userId, and resource fields but the expiresOnDate will be slightly different (few ms different). [This call](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/da80b4a2102e0e4c5c79adbac6272dfab8ad5b02/lib/memory-cache.js#L63) to underscore in MemoryCache will compare all fields in the objects, determine the objects are not equal and add a duplicate item to the cache.

Subsequent requests to do a token lookup will result in duplicates being found and another token requested. That token is then added to the _entries array. The array will continue to grow one-for-one with requests and each token lookup will become slower and slower.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
