### ISSUE TITLE
Device Code request failed with AADSTS70002 error (missing credentials)

### ISSUE THREAD

**Issue by omerlh** [AzureAD/azure-activedirectory-library-for-nodejs#140]
Hey
I tried running the device code sample. I changed the client id to a valid client id in our tenant in azure, and also changed the tenant id. The request for code succeed, but after I approved the login the request for a token failed with the following error:
AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'
I think this parameter is not required in this flow, so I do not understand why the request failed.
I am not sure if it is a bug or something I am doing wrong, but I was able to reproduce it with postman. So is seems like from some reason this endpoint requires authentication. It is also consistent behavior across languages (I tried it also with C#) so I guess this is something related to Azure and something not configured correctly (although I am not sure what). I opened a [SO](http://stackoverflow.com/questions/40583172/azure-ad-requesting-a-token-using-device-code-failed-with-401) question also. I leave this issue open although this is not a bug because of the sample - I think that if I figure this out, and this is something related to how I created the application, this should be documented as part of the Readme of the sample.
Adal-node version: 0.1.22 (latest)

Thanks,
Omer

**Comment by omerlh** [comment]
The issue was the client was web application instead of a native application. Might be a good idea to document it also in the sample code. If you agree, I can create a PR.

**Comment by mzayarnyuk** [comment]
yes you MUST CREATE DESC AND MARK IT IN CODE WITH LARGE RED CHARACTERS;
and why quality of android sample is so low;
and why don't call constants in app with same titles of that keys in AD dashboard...

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
