### ISSUE TITLE
No Typescript typings

### ISSUE THREAD

**Issue by craxal** [AzureAD/azure-activedirectory-library-for-nodejs#142]
Unless I'm mistaken, there doesn't seem to be any typings for node-adal. There is a @types/adal package on npm, but this appears to be for a different package. Having type declarations for this package would be greatly appreciated!

See also DefinitelyTyped/DefinitelyTyped#12586.

**Comment by balajikris** [comment]
Can someone from the team please comment on this? [my team](https://github.com/Azure/azure-sdk-for-node) is prototyping a version of our libraries written purely in typescript and we depend on adal-node for authentication. Not having a .d.ts would be setback for us, so having some kind of idea of whether this will be supported or not will help us plan better. [tagging @amarzavery]

**Comment by mmaitre314** [comment]
I have a beginning of typings here: https://github.com/mmaitre314/CostMonitor/blob/master/CostMonitor/adal-node.d.ts
I can expand and send a PR if interested.

**Comment by SimonSchick** [comment]
Typings would be very helpful indeed.

**Comment by amarzavery** [comment]
@rayluo @kpanwar - Can someone maintaining this repo provide an ETA for this? 
FYI, There are projects like https://github.com/SitePen/dts-generator and https://github.com/Microsoft/dts-gen
that help you generate d.ts (type definition files).

**Comment by benrr101** [comment]
@amarzavery for the record, I just tried using the Microsoft/dts-gen to generate a .d.ts for adal-node -- no dice. I've logged the issue https://github.com/Microsoft/dts-gen/issues/84

**Comment by lovemaths** [comment]
@craxal @balajikris @mmaitre314 @SimonSchick @benrr101 Typings added as of version 0.1.25. Many thanks to @amarzavery for the contribution.
