### ISSUE TITLE
Token response documentation

### ISSUE THREAD

**Issue by motiazu** [AzureAD/azure-activedirectory-library-for-nodejs#143]
I looked around the repo for 30 minutes just to see what fields I should expect from the response in AcquireTokenCallback ([as someone suggested](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/79)).
Couldn't find it documented anywhere in either the docs or the code comments. And the actual code that creates that object is a series of a lot of callback and object.extend that keep referencing to different function until you meet a `JSON.parse` which is basically a dead end.
I may have missed a part of the code that actually has the fields written, but if it's there it's very hard to find.

Of course I am going to just log it and see what I get, but I suggest that at least the [sample](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/sample/client-credentials-sample.js#L88) will have a comment saying what fields are in the response, instead of just logging it.

**Comment by Walk4Muscle** [comment]
We can find the response token definition via the requiring chain :
[authentication-context.js](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/lib/authentication-context.js#L25)=>[token-request.js](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/lib/token-request.js#L27)=>[oauth2client.js](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/lib/oauth2client.js#L43)
```
var TOKEN_RESPONSE_MAP = {};
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.TOKEN_TYPE] = TokenResponseFields.TOKEN_TYPE;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.ACCESS_TOKEN] = TokenResponseFields.ACCESS_TOKEN;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.REFRESH_TOKEN] = TokenResponseFields.REFRESH_TOKEN;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.CREATED_ON] = TokenResponseFields.CREATED_ON;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.EXPIRES_ON] = TokenResponseFields.EXPIRES_ON;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.EXPIRES_IN] = TokenResponseFields.EXPIRES_IN;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.RESOURCE] = TokenResponseFields.RESOURCE;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.ERROR] = TokenResponseFields.ERROR;
TOKEN_RESPONSE_MAP[OAuth2ResponseParameters.ERROR_DESCRIPTION] = TokenResponseFields.ERROR_DESCRIPTION;
```
Which should be a standard OAuth2 response token structure.
