### ISSUE TITLE
AcqureTokenSilentAsync function is missing for AuthenticationContext class

### ISSUE THREAD

**Issue by lindblad** [AzureAD/azure-activedirectory-library-for-nodejs#144]
The function gets in user identity as the last argument and returns access token with user as a "sub" subject field. The function is available in dot-net library for the same class. Please implement this function for the javascript library as well.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
