### ISSUE TITLE
Lacking support for requesting tokens 'on behalf of' another client

### ISSUE THREAD

**Issue by simonejsing** [AzureAD/azure-activedirectory-library-for-nodejs#146]
In the C# API you can request a token on behalf of another client by providing a 'UserAssertion' token provider. However, this is not possible in the JS library.

We need this functionality, and are looking to hack it together ourselves, but would be nice if this was supported from the framework.

**Comment by ben-m-lucas** [comment]
PR #159 submitted to address this issue.
