### ISSUE TITLE
Potential caching bug in token-request.js

### ISSUE THREAD

**Issue by Dogmans** [AzureAD/azure-activedirectory-library-for-nodejs#147]
Tokens never pulled from the cache due to incorrect key / query.

**Method I am using:**

context.acquireTokenWithUsernamePassword(
        setting.resource,
        setting.authWithCreds.username,
        setting.authWithCreds.password,
        setting.authWithCreds.clientId,
        callback);

**function that does not work as desired**

TokenRequest.prototype._createCacheQuery = function() {
  var query = {
    **clientId : this._clientId**
  };

  if (this._userId) {
    query.userId = this._userId;
  } else {
    this._log.verbose('No userId passed for cache query.');
  }

  return query;
};

**Reason**

cache entry has _clientId and not clientId so it will continue to add more and more tokens to the cache rather than reading from it

**Comment by Dogmans** [comment]
Will investigate whether token response field userId is not populated in cached token or whether there is something else going on.

**Comment by bryceg** [comment]
I just ran into this also.  Tested acquireTokenWithClientCredentials in a loop and never got the same token returned.

**Comment by eHealthManny** [comment]
I think this may be related to an issue we are having that is causing cpu usage to slowly creep up indefinitely. 

Since we end up with so many tokens in the function CacheDriver.prototype._updateRefreshTokens the call to CacheDriver._removeMany  starts taking extremely long to return and blocks the server.

Here is a snapshot of a CPU profiler we ran:
![image](https://user-images.githubusercontent.com/19152579/37442808-b2544c6c-27de-11e8-94e2-e7177dfa860f.png)

**Comment by Dogmans** [comment]
I fixed it on my branch if you want to pick that up.
See fix here:
https://github.com/Dogmans/azure-activedirectory-library-for-nodejs/commit/c6d52e7942d8f6786551daeb936d1c4809cacbe6

**Comment by amarzavery** [comment]
@bryceg 
> I just ran into this also. Tested acquireTokenWithClientCredentials in a loop and never got the same token returned.

For the service principal credentials there is no concept of storing the tokens. Adal caches the clientid and the secret and would then get a new token from ADAL service every time a request is made to acquireToken.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
