### ISSUE TITLE
Multi-factor Auth Issues

### ISSUE THREAD

**Issue by Tadimsky** [AzureAD/azure-activedirectory-library-for-nodejs#151]
Hey!
I'm running into the following error with some of the requests (often happens when accessing the site using Chrome instead of Edge). This is likely because Edge is connected to my Windows account which is the one I'm signing in with:

**Error: Get Token request returned http error: 400 and server response:** 
```
{
    "error": "interaction_required",
    "error_description": "AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: 5058bf6a-b266-444a-bf5f-a68724b53600\r\nCorrelation
 ID: b6a65466-04dc-4929-89b4-6ac81e5b31f1\r\nTimestamp: 2017-03-22 01:47:49Z",
    "error_codes": [50079],
    "timestamp": "2017-03-22 01:47:49Z",
    "trace_id": "5058bf6a-b266-444a-bf5f-a68724b53600",
    "correlation_id": "b6a65466-04dc-4929-89b4-6ac81e5b31f1",
    "claims": "{\"access_token\":{\"polids\":{\"essential\":true,\"Values\":[\"bd8d9305-ee44-4c9e-87a9-45bc878db6e1\"]}}}"
}
```

Any ideas what I can do to resolve this?

**Comment by Tadimsky** [comment]
Ping. anyone know what to do?

**Comment by danieldobalian** [comment]
@Tadimsky sorry about the really late answer.  This error happens when the resource requires extra claims (in this case MFA) from the access token. To handle it, the app needs to take the string from `claims`, and append it onto a new interactive authentication request. Then that new access token will have the necessary claims to comply with the Conditional Access policy (50079 == MFA).

**Comment by spreadzz** [comment]
@danieldobalian, it's not clear from your answer if this is possible with the ADAL library?
If so could you show some samples of code?

**Comment by mahpour** [comment]
@danieldobalian can you please be more collaborative ? your comments doesn't have very clear directions on what exactly need to be done.
