### ISSUE TITLE
Getting error the request body must contain the following parameter 'client_secret or client_assertion' 

### ISSUE THREAD

**Issue by gurusamy** [AzureAD/azure-activedirectory-library-for-nodejs#152]

**Comment by gurusamy** [comment]
assertion is passed, but still getting this error

**Comment by jorishermans** [comment]
I have the same issue here ...

**Comment by Coderrob** [comment]
This is almost a absolute requirement in order to authenticate with Microsoft Partner Center Services...

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
