### ISSUE TITLE
remove need for dynamic access to package.json to obtain lib version (util.js)

### ISSUE THREAD

**Issue by aappddeevv** [AzureAD/azure-activedirectory-library-for-nodejs#155]
When trying to add node-adal into a larger bundle, the runtime dependency on a package.json causes bundling schemes motivate a runtime failure since the package.json cannot be accessed from the larger bundle.

**Comment by akos-sebestyen** [comment]
👍 Please!

**Comment by morrisjn** [comment]
I would also love this fix! Thank you.

**Comment by tomflenniken** [comment]
The recommended approach for Azure functions is to webpack the deployed files (see https://github.com/Azure/azure-functions-pack). Adal-node is incompatible with this approach and requires us to include the adal-node packages as a separate node_module. This causes significant performance degradation (cold start times go from 5-7 seconds to ~30).

**Comment by akos-sebestyen** [comment]
@tomflenniken we had the exact same issue. See this workaround.
https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/165

**Comment by lovemaths** [comment]
@akos-sebestyen Thank you for your PR, we will do a new release this week with your PR.
