### ISSUE TITLE
Username or passwords with `string.replace` patterns will fail

### ISSUE THREAD

**Issue by forivall** [AzureAD/azure-activedirectory-library-for-nodejs#157]
If the second argument of `str.replace()` contains certain patterns ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter ), login will fail because those patterns will be changed when inserted into one of your templates for WS-security SAML stuff, etc.

Possible solutions:
1. Escape all non-literal strings used by `string.replace`
2. Wrap all non-literal strings used by `string.replace` with a function like so `TEMPLATE.replace(PATTERN, value)` -> `TEMPLATE.replace(PATTERN, function() {return value}))`
3. Use `_.template` instead of string.replace where applicable.

I'll be creating a fork for now since this is affecting us, and i'll be using solution #2.

See linked PR for test case.

**Comment by mherro** [comment]
Would be great to get this fixed. I just spent a day debugging an issue that was ultimately caused by this bug.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by forivall** [comment]
Thanks! I'm no longer working at the company where I used ADAL js (and this was back in 2017 before `msal js` was around). So, good to hear that it'll still receive security fixes, but this issue isn't my problem anymore.
