### ISSUE TITLE
You should Add .npmignore file and not publish unneeded files

### ISSUE THREAD

**Issue by fearthecowboy** [AzureAD/azure-activedirectory-library-for-nodejs#181]
The `test/*` as is the `tsconfig.json` and other files are getting included in the package that is published.

(fyi, credscan gets angry at having credentials in the tests, and since they are in the package, it's tripping up usage of the package).

**Comment by amarzavery** [comment]
.npmignore needs to be beefed up to not include those things and a new version should be published

**Comment by lovemaths** [comment]
@fearthecowboy Could you please give us more details?
(1) Does credscan complain adal-node version 0.1.23? 
(2) Could you please let me know what words credscan doesn't like?
