### ISSUE TITLE
Dependency "xpath.js" version does not have an OSI-approved license

### ISSUE THREAD

**Issue by jeffwilcox** [AzureAD/azure-activedirectory-library-for-nodejs#185]
FYI, the `xpath.js` npm module as used does not have an OSI-approved license, which may make it difficult for others to consume and use the project, depending on their corporate policies. The module is licensed CC-SA, which is not something that should be used for software; it's an artistic license.

This is an issue; for my use case here at Microsoft, this sort of module will often require a manual legal review, and CC-SA can make the lawyers nervous for sure. However, if the project would use an OSI-approved license, it would likely get automatically approved.

I've reached out to the author of the package, as have others, and they have relicensed the project to the MIT license, which is awesome. They are hopefully going to release a new version of the package soon to `npm` which will let us update the dependency version.

Note that anyone looking to use a clearly licensed version right now could also just point their `package.json` to the specific Git repo and commit ID 93225b34837b8b26d3acb86fb5d447afbf20a8fd.

The issue tracking the license for `xpath.js` is here: https://github.com/yaronn/xpath.js/issues/20

Wanted to open an issue, and I will submit a PR once the version is published by the `xpath.js` npm module author.

**Comment by anpetral-msft** [comment]
From what I can tell, the package.json of adal-node needs to be updated to allow moving to [Jeff's proposed new 1.1.0](https://github.com/yaronn/xpath.js/pull/22) version of xpath. Right now it is locked to 1.0.* in the minor version number.


Replacing the ~ version prefix to xpath.js with ^ should allow for a seamless upgrade.

**Comment by anpetral-msft** [comment]
The original issue in xpaths.js has been closed and the package is now at version 1.1.0.
