### ISSUE TITLE
how to develop for Multi-Factor Authentication 

### ISSUE THREAD

**Issue by michaelllh** [AzureAD/azure-activedirectory-library-for-nodejs#189]
how to develop for Multi-Factor Authentication , I can not find any development document in offical website , so I want to ask whether microsoft offer some technical document to develop for Multi-Factor Authentication account?

**Comment by jmckennon** [comment]
MFA for Azure can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-howitworks).

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
