### ISSUE TITLE
low performance in generating token in acquireTokenWithUsernamePassword

### ISSUE THREAD

**Issue by Hadis-Fard** [AzureAD/azure-activedirectory-library-for-nodejs#192]
I'm using ADAL node in my application to generate security token, using `AuthenticationContext.acquireTokenWithUsernamePassword`, after passing all parameters to the the API it takes about 1 second to get the response which is  considerable in node js env, the application is on halt till receiving the token and can't proceed without token. Any tips on how to improve the performance when using this API?

**Comment by Hadis-Fard** [comment]
Any updates on this?

**Comment by prowe** [comment]
I think #188 fixes this. In the meantime you can use my fork.

**Comment by v-suhame** [comment]
Thanks @prowe, the application referred in this issue is a SQL Server connectivity driver (https://github.com/tediousjs/tedious), so improving cache wouldn't help it, as `tedious` drive deals with individual connections, but connection pooling packages that uses it will benefit from your PR 👍
