### ISSUE TITLE
Token Cache not updates correctly

### ISSUE THREAD

**Issue by jdneo** [AzureAD/azure-activedirectory-library-for-nodejs#197]
The code here: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/2badd7c19e562c22fbdaff83e2d4bd524ab30c59/lib/memory-cache.js#L63 is using `isEqual` to check if two token entries are equal or not. But sometimes, `addElement` is just an update of `element`, (All the fields are equal except the `expiresOn`)

For example:
![image](https://user-images.githubusercontent.com/6193897/38725698-bd58e078-3f3a-11e8-835d-8494242c138e.png)

![image](https://user-images.githubusercontent.com/6193897/38725722-d117a5a4-3f3a-11e8-9176-dd4a782cf8b3.png)

Then, after `add` method, the token cache will have two tokens which are duplicated.

After that, when we trigger `find` for the token cache, it will cause `More than one token matches the criteria.  The result is ambiguous` error. 

Here: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/9aa56725c95981f5d8c461db5b81c7cc62884988/lib/cache-driver.js#L223

**Comment by prowe** [comment]
Could this be resolved by #188 ?

**Comment by jdneo** [comment]
Looks good. Thanks

**Comment by navyasric** [comment]
Closing as this seems to be resolved.

**Comment by jdneo** [comment]
@navyasric 

May I ask why you close this issue? The code there hasn't got any updates. The PR referenced by @prowe is still open.
