### ISSUE TITLE
Token Cache not updates correctly

### ISSUE THREAD

**Issue by jdneo** [AzureAD/azure-activedirectory-library-for-nodejs#199]
I have to create a new issue here because the original one #197 is closed by mistake and no further response after that.

------------------------------

The code here: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/2badd7c19e562c22fbdaff83e2d4bd524ab30c59/lib/memory-cache.js#L63 is using `isEqual` to check if two token entries are equal or not. But sometimes, `addElement` is just an update of `element`, (All the fields are equal except the `expiresOn`)

For example:
![image](https://user-images.githubusercontent.com/6193897/38725698-bd58e078-3f3a-11e8-835d-8494242c138e.png)

![image](https://user-images.githubusercontent.com/6193897/38725722-d117a5a4-3f3a-11e8-9176-dd4a782cf8b3.png)

Then, after `add` method, the token cache will have two tokens which are duplicated.

After that, when we trigger `find` for the token cache, it will cause `More than one token matches the criteria.  The result is ambiguous` error. 

Here: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/9aa56725c95981f5d8c461db5b81c7cc62884988/lib/cache-driver.js#L223

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by royrliu** [comment]
> All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

Hi 
Do you know how to solve the flowing issue? Or will MSAL provide the version of node.js for devicelogin?

[AzureAD/azure-activedirectory-library-for-nodejs#215](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/215)
This could be migrated to MSAL otherwise but the Node.js version doesn't support OAuth Device Flow.
