### ISSUE TITLE
Tokens not cached when obtained by refresh token

### ISSUE THREAD

**Issue by hajekj** [AzureAD/azure-activedirectory-library-for-nodejs#200]
When using `acquireTokenWithRefreshToken` the obtained token doesn't get cached which makes this library hard to use with Passport.js. Is there any reason why the token doesn't get cached? You could simple add it to the cache just like `getTokenWithDeviceCode` does - https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/9aa56725c95981f5d8c461db5b81c7cc62884988/lib/token-request.js#L578.

An alternative workaround is to push it into the cache manually like explained here: https://hajekj.net/2018/04/28/using-adal-for-node-js-with-passport-js/

**Comment by jmckennon** [comment]
https://github.com/AzureAD/passport-azure-ad could help with your issue--and thank you for providing a workaround. Additionally, we'll be writing some middleware code in the modern `msal js` over the next few quarters.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
