### ISSUE TITLE
WS-Trust RST request returned http error: 503 and server response

### ISSUE THREAD

**Issue by przemyslawpluta** [AzureAD/azure-activedirectory-library-for-nodejs#201]
We're using `adal-node@0.1.28` and getting increased amount of errors when users try to log in with below response ... after few retires we user eventually manages to log in but we haven't seen this issue before only past few weeks.

```
WS-Trust RST request returned http error: 503 and server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
```

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
