### ISSUE TITLE
Why is resource a GUID?

### ISSUE THREAD

**Issue by gregdegruy** [AzureAD/azure-activedirectory-library-for-nodejs#202]
In the code example I see
var resource = '00000002-0000-0000-c000-000000000000'; // URI that identifies the resource for which the token is valid.

In my example I was able to generate a token using
var resource = 'https://mssmartsheet.api.crm.dynamics.com';

**Comment by danieldobalian** [comment]
They're interchangeable in many cases. The GUID is the AppID of the resource. In the example above, that's the GUID of Azure AD Graph API.
