### ISSUE TITLE
Bug in Business Central Authentication, Works with Dynamics CRM Online

### ISSUE THREAD

**Issue by gregdegruy** [AzureAD/azure-activedirectory-library-for-nodejs#208]
Context here
https://stackoverflow.com/questions/52787331/dynamics-business-central-azure-ad-adal-unauthorized

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
