### ISSUE TITLE
Support client supplied https options

### ISSUE THREAD

**Issue by chrmarti** [AzureAD/azure-activedirectory-library-for-nodejs#209]
Proxy and certificate support in Node.js is not integrated with the OS settings. To work around that we would need a way to set the `agent` and `ca` properties on the options to `https.get` and `https.request` calls ADAL for Node makes.

Will this be supported in MSAL?

**Comment by jmckennon** [comment]
Setting `agent` is possible today in `msal js`. If by `ca` you mean conditional access, this is also possible through Azure settings (see https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview), though is not directly supported in the server team's implementation of the implicit flow.  Upon implementing the Auth-Code flow in `msal js` over the next few months, we will specifically be able to surface sub-errors that help with some general CA use cases.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
