### ISSUE TITLE
support oauth v2

### ISSUE THREAD

**Issue by bryanchen-d** [AzureAD/azure-activedirectory-library-for-nodejs#210]
the current version only support v1. Is there a plan to support the oauth v2 flow?

**Comment by jmckennon** [comment]
This repo will only support v1 endpoints, however `msal js` supports both v1 and v2.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
