### ISSUE TITLE
[Question] Support for custom token cache?

### ISSUE THREAD

**Issue by carlosscastro** [AzureAD/azure-activedirectory-library-for-nodejs#211]
ADAL.NET allows to provide a custom token cache. Does ADAL for nodejs provide such a functionality? 

We, at Microsoft Bot Framework, develop SDKs in multiple languages and we are making sure that the same features are supported in the different ADAL implementations. We'd lke to allow our users to use redis or other more durable token caches if they need to.

Thanks

**Comment by jmckennon** [comment]
The only caches supported in js implementations today are `session` and `local`. This may change in the distant future, but we have no plans to do so yet. We're confident in our ability to safely store secrets locally.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
