### ISSUE TITLE
retrieve data

### ISSUE THREAD

**Issue by anujaunds** [AzureAD/azure-activedirectory-library-for-nodejs#212]
Hi,

Could you let me i get access token with adal-node , But i am unable to retrieve data through api url. i tried with .acquireToken() function. i was see this "acquireToken requires a function callback parameter" error with my app.js could you please let me how i resolved this problem.

Regards,
Anuj Sharma

**Comment by jmckennon** [comment]
I know it has been quite a bit of time, and we're sorry for the delayed response. If you're still having issues, we recommend completely moving to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js).

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by jmckennon** [comment]
Closing this as we're assuming it's no longer a problem. Again, we recommend all users to onboard to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js).
