### ISSUE TITLE
Support for client assertion to get access tokens

### ISSUE THREAD

**Issue by riteshranjan007** [AzureAD/azure-activedirectory-library-for-nodejs#214]
Currently there is no support for getting access tokens using client assertion 

as mentioned here - https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/client-assertion

AuthenticationContext.prototype.acquireTokenWithAuthorizationCode = function(authorizationCode, redirectUri, resource, clientId, clientSecret, callback)

There should be a another method which should accept application private key and thumbprint.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
