### ISSUE TITLE
Error in login: "Entry not found in cache"

### ISSUE THREAD

**Issue by nasirvi** [AzureAD/azure-activedirectory-library-for-nodejs#215]
I am running into login error, any guidance on resolving or troubleshooting this issue will help.

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BDUNS3J7W to authenticate.
Error: Entry not found in cache.
at Logger.createError (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\log.js:216:13)
at TokenRequest. (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\token-request.js:526:40)
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\token-request.js:148:20
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\cache-driver.js:366:7
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\cache-driver.js:301:7
at Request._callback (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\util.js:130:7)
at Request.self.callback (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:185:22)
at Request.emit (events.js:189:13)
at Request. (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:1157:10)
at Request.emit (events.js:189:13)
at IncomingMessage. (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:1079:12)
at Object.onceWrapper (events.js:277:13)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1103:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nasirvi** [comment]
Is there any workaround for this issue? Found one more similar issue but that does seem to solve it for us. https://github.com/Azure/azure-xplat-cli/issues/2203

**Comment by guybartal** [comment]
happens to me as well... is this going to get fixed?

**Comment by aaomidi** [comment]
This is happening to me as well.

**Comment by aaomidi** [comment]
So I've found a pretty fun workaround for this problem... 


https://github.com/microsoft/azuredatastudio/blob/48b2cbb0bfe3de49a9dfc4561b62eb737b3cde2d/extensions/azurecore/src/account-provider/azureAccountProvider2.ts#L337-L355

You have to modify the token object and store it separately.

**Comment by royrliu** [comment]
@nasirvi 
Hi, I also encountered the same problem.
Have you solved this problem?

Does anyone knows
Has this example not been running all the time?
If, using the previous version of node.js, will it work?

**Comment by nasirvi** [comment]
> @nasirvi
> Hi, I also encountered the same problem.
> Have you solved this problem?
> 
> Does anyone knows
> Has this example not been running all the time?
> If, using the previous version of node.js, will it work?

@royrliu it was fixed for us by changing the azure portal password which was by coincidence.

**Comment by aaomidi** [comment]
I just stopped using this.

**Comment by mstewio** [comment]
I received this error when I attempted to authenticate using my company's Enterprise account where I am not a global admin. I created a trial Azure subscription using my personal Outlook account and DID NOT receive this error.

**Comment by BernhardRode** [comment]
Same issue here

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
