### ISSUE TITLE
Got error when trying to get access token in nodejs using azure, AADSTS50058: A silent sign-in request was sent but no user is signed in

### ISSUE THREAD

**Issue by anfasci** [AzureAD/azure-activedirectory-library-for-nodejs#222]
StatusCodeError: 400 - "{"error":"invalid_grant","error_description":"AADSTS50058: A silent sign-in request was sent but no user is signed in.\r\nTrace ID: 05db5c6a-155c-4870-9bca-a518b5931900\r\nCorrelation ID: 1e8372d0-c1ba-4070-88d7-597e9cb5cb2c\r\nTimestamp: 2019-08-14 12:04:42Z","error_codes":[50058],"timestamp":"2019-08-14 12:04:42Z","trace_id":"05db5c6a-155c-4870-9bca-a518b5931900","correlation_id":"1e8372d0-c1ba-4070-88d7-597e9cb5cb2c","error_uri":"https://login.microsoftonline.com/error?code=50058\"}"

URL= 'https://login.microsoftonline.com/' + process.env.TENANT_ID + '/oauth2/token',

I am trying to implement azure login in nodejs scheduler app, and then want to upload file to sharepoint.
First i need to login, then get accesstoken,refresh token, admin accesstoken etc.
When i try to get accesstoken , i got error like this.
Can you help me.
Here no use of any front end.

async function init(parsedBody) {
var jwtToken = await sharepointAuth.getJWTToken(parsedBody);
console.log("jwtToken:",jwtToken)
const config = {
JWK_URI: appConstants.JWK_URI,
ISS: appConstants.ISS,
AUD: appConstants.conf.AUD,
};
console.log(config)
await azureJWT.verify(jwtToken, config).then(async () => {
console.log("----------------------------------")
var fileName = 'analytics.min.js';
var filePath = './public/analytics.min.js';
var userAccessToken = await getAccessToken(jwtToken);
console.log("userAccessToken:", userAccessToken);
var accessTokenObj = await sharepointAuth.getAdminAccessToken();
accessToken = accessTokenObj.access_token;
console.log("accessToken:", accessToken)
fs.readFile(filePath, { encoding: null }, function (err, data) {
const relativeUrl = web/GetFolderByServerRelativeUrl('${selectedFolderName}');
const SHAREPOINT_HEADER = {
'Authorization': Bearer ${accessToken},
"Content-Type": application/json;odata=verbose,
'Accept': 'application/json;odata=verbose',
}
const options = {
method: "POST",
uri: ${SHAREPOINT_URI}${relativeUrl}/Files/add(url='${fileName}',overwrite=true),
headers: SHAREPOINT_HEADER,
body: data
};
console.log(options)
rp(options)
.then(() => {
// POST succeeded...
console.log('File uploaded!');
})
.catch((error) => {
// POST failed...
console.log("File Upload Error: ", error.toString());
});
});
});
}
const request = require("request");
const endpoint = "https://login.microsoftonline.com/tenentId/oauth2/token";
const requestParams = {
grant_type: "client_credentials",
client_id: "ClientId",
client_secret: "Secret",
resource: "ClientId"
};

request.post({ url: endpoint, form: requestParams }, function (err, response, body) {
if (err) {
console.log("error");
}
else {
console.log("Body=" + body);
let parsedBody = JSON.parse(body);
if (parsedBody.error_description) {
console.log("Error=" + parsedBody.error_description);
}
else {
console.log("parsedBody : " + parsedBody);
console.log("Access Token=" + parsedBody.access_token);
init(parsedBody);
}
}
});

function getAccessToken(jwtToken) {
  return new Promise(async (resolve) => {
    try {
      const options = {
        method: 'POST',
        uri: appConstants.OTB_URL,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        formData: {
          grant_type: appConstants.OTB_GRANT_TYPE,
          client_id: appConstants.conf.AUD,
          client_secret: appConstants.conf.CLIENT_SECRET,
          resource: appConstants.OTB_RESOURCE_URI2,
          client_assertion_type: appConstants.OTB_CLIENT_ASSERTION_TYPE,
          requested_token_use: appConstants.OTB_REQ_TOKEN_USE,
          scope: appConstants.OTB_SCOPE,
          assertion: jwtToken,
        },
      };
      console.log("options:", options)
      await rp(options)
        .then(async (parsedBody) => {
          // POST succeeded...
          const result = JSON.parse(parsedBody);
          console.log("****************************************** result", result)
          refreshToken = result.refresh_token;

          resolve(result.access_token);
        })
        .catch((error) => {
          // POST failed...
          console.log('getAccessTokenRequestError: ', error.toString());
          resolve(appConstants.ACCESS_TOKEN_ERROR);
        });
    } catch (error) {
      console.log('getAccessTokenRequestPromiseError: ', error.toString());
      resolve(appConstants.MIDDLEWARE_ERROR);
    }
  });
}

**Comment by jmckennon** [comment]
Hi @anfasci, sorry for the delayed response. If you're still seeing issues, please comment and we can try to remedy them. My best guess by seeing this part of your code is that you're not explicitly logging in before trying to obtain a token. I think I'll need more info to further guide you, is this all the code you've written? (Additionally, wrap everything in three backtics ``` on either side to replicate code styling for readability).

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by jmckennon** [comment]
Closing as we're assuming this is no longer an issue from the delayed response. Again, we recommend all users to move to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js).
