### ISSUE TITLE
It is not possible to identify with Subject Name and Issuer Authentication 

### ISSUE THREAD

**Issue by salowenh** [AzureAD/azure-activedirectory-library-for-nodejs#224]
Currently it's possible to acquire token using Subject name and issuer authentication only when using the  [.net lib](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet)
This should be available for the nodejs library as well as it's more secure and stands with various security requirements for cert's auto-renew

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, are still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
