### ISSUE TITLE
Remove dependency on deprecated Request

### ISSUE THREAD

**Issue by aflinchb** [AzureAD/azure-activedirectory-library-for-nodejs#229]
Request is being deprecated: https://github.com/request/request/issues/3142 and this library currently has a dependency.

**Comment by jmckennon** [comment]
@aflinchb Thanks for the heads up; this library is also effectively in maintenance mode. We'll only be making changes for high priority security fixes. We recommend users move to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). We are starting work on an `msal-node` as well [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/4)  which will be baked into the same `msal js` repo. Closing as we won't be making any changes with respect to the `request` deprecation.
