### ISSUE TITLE
Sharepoint SPFX error

### ISSUE THREAD

**Issue by nilesh-verma** [AzureAD/azure-activedirectory-library-for-nodejs#232]
In using my sharepoint framework project , on serving the project it gives the error

Error - [webpack] 'dist':
./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib'
resolve 'fs' in 'D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib'
  Parsed request is a module
  using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib\node_modules doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib\lib doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\node_modules doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\lib doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\node_modules doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\lib doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\node_modules doesn't exist or is not a directory
      D:\sharepoint\PeckBrtother_CodeRepository\lib doesn't exist or is not a directory
      D:\sharepoint\node_modules doesn't exist or is not a directory
      D:\sharepoint\lib doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      D:\lib doesn't exist or is not a directory
      looking for modules in D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\node_modules
        using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib
        using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\package.json (relative path: ./lib)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules
        using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\lib
        using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\package.json (relative path: ./lib)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\fs\package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\package.json (relative
path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\package.json (relative
path: ./lib/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\fs is not a file
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\package.json (relative path: ./lib/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\node_modules\fs doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\lib\fs doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\fs.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\lib\fs doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\sharepoint\PeckBrtother_CodeRepository\DemoSite\CRM_API\node_modules\request\node_modules\fs.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
