### ISSUE TITLE
Replace the deprecated and vulnerable dependency package `request`

### ISSUE THREAD

**Issue by joonaojapalo** [AzureAD/azure-activedirectory-library-for-nodejs#240]
The direct dependency package `request` has been deprecated in Feb 2020 (https://www.npmjs.com/package/request). All versions of `request` including the latest one are affected by prototype pollution vulnerability (https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-21913/summary)

Maintainers of the package have composed the list of alternative libraries for replacement: https://github.com/request/request/issues/3143

**Comment by sameerag** [comment]
Thanks for bringing this to our notice. Will update once we arrive at a solution

**Comment by sameerag** [comment]
Started working on this, will have a PR up soon.

**Comment by sameerag** [comment]
Final testing in progress, please track #243 for this. Currently up as a `draft`

**Comment by garyfungwelab** [comment]
Hi, any update?

**Comment by vinu-vrize** [comment]
hi @sameerag, is the PR ready to be merged. What's the latest update on the issue closure.

**Comment by sameerag** [comment]
Update: We are running into some issues with the `nock` mocks for some `post` requests before the holidays. I just picked this up and working on resolving them. Will be opening one more PR and once it passes locally, will be merging both. Please expect an update soon.

**Comment by sameerag** [comment]
Update: All nock issues are addressed except one use case where axios seems to make an exta NW call throwing the nock test off. However the PR is available now for review, will test this end to end for couple days and then plan a release.
