### ISSUE TITLE
Token Generation

### ISSUE THREAD

**Issue by entity** [AzureAD/azure-activedirectory-library-for-nodejs#242]
Hi all,

I'm currently new to the Azure space, I'm looking to integrate Azure Sign Sign-On for the company utilising NodeJS and Express (as shown in your example / demo), it works all fine but after a while I'd get;
```
AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
```

How can I fix this, do I need to call another URL to change this, I've tried deleting their cookie and sending them back to login but seems to still not fix the state.

Thanks.

**Comment by cameronstubber** [comment]
Im struggling with similar issues. Everything is working on my node/express app. but after 1 hour when the token expires I dont seem to be able to get a new one even though I send the call to get it.

**Comment by entity** [comment]
> Im struggling with similar issues. Everything is working on my node/express app. but after 1 hour when the token expires I dont seem to be able to get a new one even though I send the call to get it.

I fixed the issue myself, I needed to generate a refresh token, though this was a mess to configure.
