### ISSUE TITLE
Allow to specify scope when using device code authentication

### ISSUE THREAD

**Issue by ramya-rao-a** [AzureAD/azure-activedirectory-library-for-nodejs#245]
This issue is a follow up from https://github.com/Azure/azure-sdk-for-node/issues/5190 which was logged for the `ms-rest-azure` package which in turn uses the `adal-node` package for all the auth work

The above linked issue uses https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#protocol-diagram as a reference and expects the ability of passing the scope when making the request to the `/devicecode` endpoint.

When I looked into the adal-node package, I see the scope being set to `openid` at https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/023fb2e3913e522091368c58d473b0042e6d0c74/lib/token-request.js#L207, and that too only when the grant type is not device code, client credentials and auth code

Can someone provide some clarification on what one should do when they need to set the scope?

cc @jefjos who logged the original issue and should be able to answer any follow up question on the issue

**Comment by sameerag** [comment]
@ramya-rao-a Is this still an issue with msal-node?

**Comment by sameerag** [comment]
Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
