### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by tharaka86** [AzureAD/azure-activedirectory-library-for-nodejs#246]
I have below code, which it now deployed to a azure app service (https://xxxx.azurewebsites.net/).

I have set the url in Redirect URIs under active directory app registration but get the below cors issue

Access to fetch at 'https://login.microsoftonline.com/xxxx.onmicrosoft.com/oauth2/token?api-version=1.0' from origin 'https://xxxx.azurewebsites.ne' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Am i missing any config here

    var AuthenticationContext = require('adal-node').AuthenticationContext;

    const authenticate = (): any =>{   

    var authorityHostUrl = 'https://login.microsoftonline.com';
    var tenant = 'xxxx.onmicrosoft.com'; 
    var authorityUrl = authorityHostUrl + '/' + tenant;
    var applicationId = '2sdsdwewe-232jkdksdsdsadfsfdsdf'; 
    var clientSecret = 'sdfer245dwfsfw3rt345r342fwfwefwf'; 
    var resource = 'api://sdfwerwerwrwerwerwrewrwer'; 
    
    var context = new AuthenticationContext(authorityUrl);
    
    context.acquireTokenWithClientCredentials(resource, applicationId, clientSecret, (err: { stack: string; }, tokenResponse: any)=> {
      if (err) {
        console.log('well that didn\'t work: ' + err.stack);
      } else {
        console.log(tokenResponse);
      }
    });
   }

**Comment by LoganStewart** [comment]
I get a similar issue but from localhost:3000

**Comment by tharaka86** [comment]
> I get a similar issue but from localhost:3000

Yes same with me on localhost, that why i tried to deployed to see if it make any difference

**Comment by hectormmg** [comment]
Hey @tharaka86 is this the same issue you described on our [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2970)? If so, the reason here may be that your AAD app is configured as a SPA (which is classified as a Public Client applications) type and the Client Credential flow is only available to Confidential Clients.
