### ISSUE TITLE
Security vulnerability for underscore

### ISSUE THREAD

**Issue by jajens** [AzureAD/azure-activedirectory-library-for-nodejs#255]
Snyk published a low severity Arbitrary Code Injection vuln for any version of underscore below 1.13.0-2 or 1.12.1 on 3/29/21 which is picked up in our security scans for adal-node: https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984

It looks like the current version of adal-node 0.2.2  is using version 1.9.1 of underscore.  
    "underscore": {
      "version": "1.9.1",
      "resolved": "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz",
      "integrity": "sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg=="

Any chance underscore can be upgraded to a newer version to resolve the vulnerability?

**Comment by jasonnutter** [comment]
@jajens First, we are in the process of moving the code for this library to the MSAL.js repo, where we have addressed this alert: https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/74de607ea41f416a06044746347ecfed08f135b3

Second, note that adal-node use `underscore@>= 1.3.1`, meaning when it is installed in your app, it will pick up the latest `1.x` version, so you can pick up the latest by regenerating your package-lock in your app.

**Comment by jajens** [comment]
Thanks for the response, closing the issue.
