### ISSUE TITLE
Security vulnerability for uuid@3.x.x

### ISSUE THREAD

**Issue by sindilevich** [AzureAD/azure-activedirectory-library-for-nodejs#261]
Currently, installing `adal-node@latest`, produces the following message:

> deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

Please upgrade to the latest version of `uuid` for better security/stronger random uuid's.

**Comment by jasonnutter** [comment]
@sindilevich `Math.random` is only used by `uuid@3.x` in browser scenarios, which is out of scope for ADAL Node: https://github.com/uuidjs/uuid/blob/e2d731463b680c5b816d144f66feef902586410e/lib/rng-browser.js#L28

Furthermore, please consider updating to MSAL Node: https://www.npmjs.com/package/@azure/msal-node

Closing, as no further action needed.

**Comment by sindilevich** [comment]
@jasonnutter, thank you for pointing out the real scope of the usage of `Math.random()` in `uuid@3.x.x`!

However, `adal-node` is a transitive dependency of many other libraries, such as `tedious`. Meaning projects wish to connect to an MS SQL server would install `adal-node` and produce a scaresome warning message about the need to upgrade to a newer version of `uuid`.

Since `uuid@3.x.x` is no real harm in a node.js environment, the severity of the issue tremendously drops. But having a warning-free dependency tree may be worth the effort upgrading the library. Would a PR with an upgrade help to take the issue forward?

Thank you in advance!
