### ISSUE TITLE
Security: Update jws dependency version

### ISSUE THREAD

**Issue by ahmetalpbalkan** [AzureAD/azure-activedirectory-library-for-nodejs#45]
Package currently depends on `jws@1.x.x`. There's been a security update on that package you should take.

While installing `azure-cli` package, it raises a visible warning saying

    npm WARN deprecated jws@1.0.1: Security update: Versions below 3.0.0 are deprecated.

https://github.com/Azure/azure-xplat-cli/issues/1691

Can you please fix this?

**Comment by RandalliLama** [comment]
@ahmetalpbalkan fixed in v0.1.13
 3a2dcb9
