### ISSUE TITLE
When enabling logging for adal-node, the log for the RST request with client creds contains the user's password

### ISSUE THREAD

**Issue by michaeljm** [AzureAD/azure-activedirectory-library-for-nodejs#46]
After enabling the log on `adal.Logging` at verbose level and making a token request with `acquireTokenWithClientCredentials`, the log output contains a clear text version of the password.

Look for the following in the logs:
```
{GUID} - WSTrustRequest: VERBOSE: Sending RST to [...]
<s:Envelope [...]>
  <wsse:Username>{UserName}</wsse:Username>
  <wsse:Password>{ClearTextPassword}</wsse:Password>
```

**Comment by RandalliLama** [comment]
@michaeljm Fixed in v0.1.13
 3a2dcb9
