### ISSUE TITLE
Error messages must be interpreted to know whether credentials were wrong or transport failed

### ISSUE THREAD

**Issue by michaeljm** [AzureAD/azure-activedirectory-library-for-nodejs#47]
We're building a feature where there's a secure credential store on the client, from which we get the user name and password to use in the `acquireTokenWithClientCredentials` call. If the user name and password are invalid, we need to revoke them from the store.

Currently, it's not too obvious from the error whether the credentials were bad (e.g. expired, with a typo, etc...) or whether there was an issue at the transport level (e.g. failure to connect to remote host, TLS handshake failed, etc...).

_It would be helpful to get detailed feedback on this in the errors_. E.g. "error.transportError = true;".

Sample cred errors:
1. Invalid username

```
Server returned an unknown AccountType: undefined
```
1. Bad credentials

```
WS-Trust RST request returned http error: 500 and server response: [...]
  <s:Fault>
    <s:Code>
      <s:Value>s:Sender</s:Value>
      <s:SubCode>
        <s:Value>a:FailedAuthentication</s:Value>
[...]
  <s:Reason>
    <s:Text>ID3242: The security token could not be authenticated or authorized.</s:Text>
[...]
```

Sample transport errors:

```
  <s:Subcode>
    <s:Value>a:ActionNotSupported</s:Value>
  </s:Subcode>
[...]
  <s:Reason>
    <s:Text xml:lang="en-US">The message with Action
'http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue'
cannot be processed at the receiver, due to a ContractFilter mismatch
at the EndpointDispatcher. This may be because of either a contract
mismatch (mismatched Actions between sender and receiver) or a
binding/security mismatch between the sender and the receiver.  Check
that sender and receiver have the same contract and the same binding
(including security requirements, e.g. Message, Transport, None).
    </s:Text>
  </s:Reason>
```

```
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
```

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
