### ISSUE TITLE
isExpiresWithinTolerance validation not really validating anything

### ISSUE THREAD

**Issue by crwilcox** [AzureAD/azure-activedirectory-library-for-nodejs#53]
This function is not very useful as it currently sets the two compared dates to the same object.  My guess is after fixing this your validation might fail also.  Included is what I am doing for the python tests

``` javascript
function isExpiresWithinTolerance(expiresOn, expired){
  if (!expiresOn) {
    console.log('no expires_on');
    return false;
  }

  // Add the expected expires_in latency.
  var expectedExpires = expired ? new Date() : Date.yesterday();
  expectedExpires = expiresOn.addSeconds(28800);
  return isDateWithinTolerance(expiresOn, expectedExpires);
}
```

This line is going to add to expiresOn and set expectedExpires to the same object:

``` javascript
expectedExpires = expiresOn.addSeconds(28800);
```

Python code for what we are doing instead:

``` python
def isExpiresWithinTolerance(expiresOn):
    # Add the expected expires_in latency.
    expectedExpires = datetime.now() + timedelta(0, 28800)
    return isDateWithinTolerance(expiresOn, expectedExpires);
```

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
