### ISSUE TITLE
Calling to graph api after user authentication

### ISSUE THREAD

**Issue by siacomuzzi** [AzureAD/azure-activedirectory-library-for-nodejs#55]
Hi,

After user is authenticated (`GET /authorize?...`), can I use his JWT (`id_token`) to call the Graph API (`https://graph.windows.net/contoso.onmicrosoft.com/users?api-version=1.0&...`)?

I want to get full user profile (including user groups).

Currently, I'm getting the following error:

#### Response body
```
{
  "odata.error": {
    "code": "Authentication_MissingOrMalformed",
    "message": {
      "lang": "en",
      "value": "Access Token missing or malformed."
    },
    "values":null
  }
}
```

#### Response headers
```
'request-id': '48c2e927-a746-42b9-8c59-49219ca5da48',
'client-request-id': '323ff27a-e589-4cea-8060-5e5c6a419d2e',
'x-ms-dirapi-data-contract-version': '1.0',
'strict-transport-security': 'max-age=31536000; includeSubDomains',
'access-control-allow-origin': '*',
'www-authenticate': 'Bearer realm="XYZ.onmicrosoft.com", error="invalid_token", error_description="Access Token missing or malformed.", authorization_uri="https://login.windows.net/XYZ.onmicrosoft.com/oauth2/authorize", client_id="00000002-0000-0000-c000-000000000000"'
```

Thanks!

**Comment by brandwe** [comment]
You must use the access token, not the id token.

**Comment by RandalliLama** [comment]
@siacomuzzi Please re-open the issue if you are still having problems.

**Comment by szarouski** [comment]
It doesn't work for me too. I tried both access token & id_token, neither works. @RandalliLama any help will be much appreciated. Thank you.
