### ISSUE TITLE
Tests for Cache Driver may have error

### ISSUE THREAD

**Issue by crwilcox** [AzureAD/azure-activedirectory-library-for-nodejs#61]
I didn't run the file but I came across the tests for cache driver and on line 93 I noticed:

```
for (var i = 0; i < cacheEntries[i].length; i++) {
        if (cacheEntries[i].isMRRT) {
          assert(cacheEntries[i]['refreshToken'] === mrrtRefreshToken, 'One of the responses refresh token was not correctly updated: ' + i);
        }
```

my guess is cacheEntries[i] is doing something you don't want.  The length I can go to is the i we are currently on?  This is going to do an odd sort of search.  you probably meant cacheEntries.length

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
