### ISSUE TITLE
WsTrust request should escape xml chars in password

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-nodejs#62]
Escape xml chars in password before creating a xml request at wstrust-request.js.

**Comment by devigned** [comment]
I think this is coming up here: https://github.com/Azure/azure-xplat-cli/issues/1918. Any update on this issue?

**Comment by weijjia** [comment]
we've already made the fix. It will be merged.

**Comment by devigned** [comment]
Thank you, @weijjia. Looking forward to getting this fixed for Azure CLI.

**Comment by weijjia** [comment]
The fix has been merged into master.

**Comment by weijjia** [comment]
fix has been merged and close the issue.
