### ISSUE TITLE
Id token subject identifier field is 'sub', not 'subject'.

### ISSUE THREAD

**Issue by aj-michael** [AzureAD/azure-activedirectory-library-for-nodejs#65]
When retrieving a userid from an idtoken, one of the fallbacks is the subject field of the idtoken. Per the spec, the field is sub. I also confirmed it against login.windows.net token endpoint.

http://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by weijjia** [comment]
merged and closed the issue for now.
