### ISSUE TITLE
When using adal-node with azure-xplat-cli, AD http calls do not honor proxy setting

### ISSUE THREAD

**Issue by jmspring** [AzureAD/azure-activedirectory-library-for-nodejs#72]
azure-activedirectory-library-for-nodejs specifies request module version >= 2.9.203.  From the package.json dependencies:  "request": ">= 2.9.203",

when used with azure-xplat-cli, it ends up using request module version 2.27.0.  From the azure-xplat-cli package.json dependencies:  "request": "2.27.0"

Proxy support in the request module was refactored in roughly around version 2.52.0 (in January of 2015).  Updating azure-activedirectory-library-for-nodejs to rely on this version or later fixes the issue with ADAL and respecting proxies when used with azure-xplat-cli.

Specific proxy settings being used (on mac and linux) are:

export HTTPS_PROXY=http://localhost:8888
export HTTP_PROXY=http://localhost:8888

On a local machine when using the azure cli, and the above proxy settings w/ no changes to which version of the request module, a man in the middle proxy sees only the connection to https://manage.azure.com (to get subscription information), it does not see the request to https://login.windows.net.

Modifying adal-node to require request 2.52.0 or newer, the request to https://login.windows.net is visible in the MITM proxy.

Submitting a small pull request with the change.

**Comment by weijjia** [comment]
pull request #73 has been merged for this. Close the issue.
