### ISSUE TITLE
Express dependency in package.json doesn't match syntax used in website-sample.js

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-nodejs#78]
`sample/package.json` declares a dependency on Express v2 but `sample/website-sample.js` initializes `express` by calling [`express()`](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/sample/website-sample.js#L32) which is Express v3 syntax.

To reproduce the issue:
1. `git clone <repo>`
2. `cd sample`
3. `npm install && node website-sample.js`

Failing output:

``` javascript
.../sample/website-sample.js:32
var app = express();
          ^
TypeError: object is not a function
    at Object.<anonymous> (.../sample/website-sample.js:32:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
