### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-nodejs#79]
I can't seem to locate API documentation for this library. Are there only samples?

**Comment by RandalliLama** [comment]
@iambmelt We don't have the docs published separately yet.  At this time the best place to find API docs is in the code.  Everything you need should be in:

https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/lib/authentication-context.js

You can produce HTML docs by installing jsdoc via npm and then running:

```
npm run-script doc
```

This should generate docs in a directory named 'out'.  Start with index.html and let us know if you have any problems.

Sorry this isn't easier at this point.

**Comment by iambmelt** [comment]
Thanks @RandalliLama! Just wanted to make sure I wasn't overlooking something obvious :) Feel free to close the issue out now :+1:
