### ISSUE TITLE
PowerBI API not supported

### ISSUE THREAD

**Issue by zzeekk** [AzureAD/azure-activedirectory-library-for-nodejs#88]
PowerBI API (resource='https://analysis.windows.net/powerbi/api') needs user/password authentication incl. ClientSecret. acquireTokenWithUsernamePassword doesnt support this scenario. 

Error message is: "AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'

**Comment by hajekj** [comment]
Related to https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/98

**Comment by ArmorDarks** [comment]
Seems like `https://analysis.windows.net/powerbi/api` no longer valid URL for Power BI. Just in case someone will get here 3 years after...

**Comment by jmckennon** [comment]
Unsupported based on #98 

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
