### ISSUE TITLE
Doesn't work now...since the V2 Graph API got released...

### ISSUE THREAD

**Issue by julianfrank** [AzureAD/azure-activedirectory-library-for-nodejs#92]
Doesn't work now...since the V2 Graph API got released...When is this going to get updated to support V2 AAd?

**Comment by molant** [comment]
HI @julianfrank,
What error are you seeing?
I can successfully get a Bearer token using user and pass but when I use it to access a resource the server says I'm not authenticated. I wonder if this is related...
Thanks!

**Comment by julianfrank** [comment]
I use the ClientID/Secret generated on the new App Model V2 Site...The Browser returns "error: The authorizationCode parameter is required. response: undefined" in the body and URL has this:"http://localhost:3000/getAToken?error=unauthorized_client&error_description=AADSTS70001%3a+Application+%27cbb12a4b-fc50-4c72-ba1f-e5c30615761e%27+is+not+supported+for+this+API+version.%0d%0aTrace+ID%3a+03c28676-bdca-490c-9580-2702216b34dd%0d%0aCorrelation+ID%3a+902cf6f9-54dc-4ff4-8801-185ce776b350%0d%0aTimestamp%3a+2015-12-09+11%3a46%3a48Z&state=TYD44UWKaNCgzoZhdJkwl7HlTwnMQI4186qKMXS_M5JT_17DoLqGJlgXp7znYOV-"...Not the Text saying that this client id is not supported for this API version

**Comment by molant** [comment]
@julianfrank In my case what I've done is to comment lines #93 and #108 from ouathclient.js: 
```js
//parameters[OAuth2Parameters.AAD_API_VERSION] = '1.0';
```
This returns a token that works with the service I'm trying to access

**Comment by julianfrank** [comment]
I believe you meant oath2client.js ...Tried but still not working...console doesnt throw any error like in #93 

![image](https://cloud.githubusercontent.com/assets/9428111/11711927/db124f88-9f4f-11e5-853c-b8877b711046.png)

**Comment by julianfrank** [comment]
I created the client id and secret in the new portal ...https://apps.dev.microsoft.com...maybe your code is built for the client id/secret created in the old AAD portal

**Comment by weijjia** [comment]
Where version you're using? To support the v2 module, you should use the version 2.0.0-pre

**Comment by julianfrank** [comment]
will try some time later...I had tried when Graph v2 just got released...

**Comment by molant** [comment]
@julianfrank Does it mean it works now?
