### ISSUE TITLE
Allow to remove or change the api-version parameters when requesting tokens

### ISSUE THREAD

**Issue by molant** [AzureAD/azure-activedirectory-library-for-nodejs#94]
The library has hardcoded `api-version=1.0` (oauthclient.js lines 93 and 108). It will be great if we could change that value programmatically or directly remove that header.
For the last day I've been investigating why the token I got from nodejs didn't worked when accessing a resource and that was the issued. The C# library doesn't seem to append that parameter.

**Comment by Tadimsky** [comment]
I'm seeing this same issue. Requesting against version 1.0 gives me this error:

> {  
>    "error":"invalid_grant",
>    "error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'd384e414-b518-4087-8736-961830660e58'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 2428f949-d8db-418c-9691-24b6277f7593\r\nCorrelation ID: 351f8663-1081-4a52-a16b-9b7399e847a3\r\nTimestamp: 2016-04-29 18:33:49Z",
>    "error_codes":[  
>       65001
>    ],
>    "timestamp":"2016-04-29 18:33:49Z",
>    "trace_id":"2428f949-d8db-418c-9691-24b6277f7593",
>    "correlation_id":"351f8663-1081-4a52-a16b-9b7399e847a3"
> }

Removing the `api-version` parameter or changing it to `beta` results in successful authorization.

Why is it allowed to authorize on a non-versioned endpoint?

**Comment by rayluo** [comment]
Thanks for all your patience. This is now fixed in [release 0.2.0](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/releases/tag/0.2.0) after we merged #186. You will still need to manually opt-in for the new behavior.
CC @DarylThayil
