### ISSUE TITLE
Support for App Model v2.0?

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-nodejs#96]
It looks like there is already support for the [App Model v2.0](https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-compare/) in the `devConvergence` branch. Is this available through npm? Or will it be released with the GA of v2.0?

**Comment by weijjia** [comment]
yes, it's available through npm, version is 2.0.0-pre.
